using System.ComponentModel;
namespace WeStrap
{
    public enum WeOffset
    {
        [Description("offset-sm-1")]
        Small1,
        [Description("offset-sm-2")]
        Small2,
        [Description("offset-sm-3")]
        Small3,
        [Description("offset-sm-4")]
        Small4,
        [Description("offset-sm-5")]
        Small5,
        [Description("offset-sm-6")]
        Small6,
        [Description("offset-sm-7")]
        Small7,
        [Description("offset-sm-8")]
        Small8,
        [Description("offset-sm-9")]
        Small9,
        [Description("offset-sm-10")]
        Small10,
        [Description("offset-sm-11")]
        Small11,
        [Description("offset-sm-12")]
        Small12,
        [Description("offset-md-1")]
        Medium1,
        [Description("offset-md-2")]
        Medium2,
        [Description("offset-md-3")]
        Medium3,
        [Description("offset-md-4")]
        Medium4,
        [Description("offset-md-5")]
        Medium5,
        [Description("offset-md-6")]
        Medium6,
        [Description("offset-md-7")]
        Medium7,
        [Description("offset-md-8")]
        Medium8,
        [Description("offset-md-9")]
        Medium9,
        [Description("offset-md-10")]
        Medium10,
        [Description("offset-md-11")]
        Medium11,
        [Description("offset-md-12")]
        Medium12,
        [Description("offset-lg-1")]
        Large1,
        [Description("offset-lg-2")]
        Large2,
        [Description("offset-lg-3")]
        Large3,
        [Description("offset-lg-4")]
        Large4,
        [Description("offset-lg-5")]
        Large5,
        [Description("offset-lg-6")]
        Large6,
        [Description("offset-lg-7")]
        Large7,
        [Description("offset-lg-8")]
        Large8,
        [Description("offset-lg-9")]
        Large9,
        [Description("offset-lg-10")]
        Large10,
        [Description("offset-lg-11")]
        Large11,
        [Description("offset-lg-12")]
        Large12,
        [Description("offset-xl-1")]
        XtraLarge1,
        [Description("offset-xl-2")]
        XtraLarge2,
        [Description("offset-xl-3")]
        XtraLarge3,
        [Description("offset-xl-4")]
        XtraLarge4,
        [Description("offset-xl-5")]
        XtraLarge5,
        [Description("offset-xl-6")]
        XtraLarge6,
        [Description("offset-xl-7")]
        XtraLarge7,
        [Description("offset-xl-8")]
        XtraLarge8,
        [Description("offset-xl-9")]
        XtraLarge9,
        [Description("offset-xl-10")]
        XtraLarge10,
        [Description("offset-xl-11")]
        XtraLarge11,
        [Description("offset-xl-12")]
        XtraLarge12,
    }
}