using System.ComponentModel;
namespace WeStrap{
	public enum WeSpacer{
	[Description("mr-auto")]
	MarginRightAuto,
	[Description("ml-auto")]
	MarginLeftAuto,
		[Description("mt-0")]
		MarginTopXtraSmall0,
		[Description("mt-1")]
		MarginTopXtraSmall1,
		[Description("mt-2")]
		MarginTopXtraSmall2,
		[Description("mt-3")]
		MarginTopXtraSmall3,
		[Description("mt-4")]
		MarginTopXtraSmall4,
		[Description("mt-5")]
		MarginTopXtraSmall5,
		[Description("mt-sm-0")]
		MarginTopSmall0,
		[Description("mt-sm-1")]
		MarginTopSmall1,
		[Description("mt-sm-2")]
		MarginTopSmall2,
		[Description("mt-sm-3")]
		MarginTopSmall3,
		[Description("mt-sm-4")]
		MarginTopSmall4,
		[Description("mt-sm-5")]
		MarginTopSmall5,
		[Description("mt-md-0")]
		MarginTopMedium0,
		[Description("mt-md-1")]
		MarginTopMedium1,
		[Description("mt-md-2")]
		MarginTopMedium2,
		[Description("mt-md-3")]
		MarginTopMedium3,
		[Description("mt-md-4")]
		MarginTopMedium4,
		[Description("mt-md-5")]
		MarginTopMedium5,
		[Description("mt-lg-0")]
		MarginTopLarge0,
		[Description("mt-lg-1")]
		MarginTopLarge1,
		[Description("mt-lg-2")]
		MarginTopLarge2,
		[Description("mt-lg-3")]
		MarginTopLarge3,
		[Description("mt-lg-4")]
		MarginTopLarge4,
		[Description("mt-lg-5")]
		MarginTopLarge5,
		[Description("mt-xl-0")]
		MarginTopXtraLarge0,
		[Description("mt-xl-1")]
		MarginTopXtraLarge1,
		[Description("mt-xl-2")]
		MarginTopXtraLarge2,
		[Description("mt-xl-3")]
		MarginTopXtraLarge3,
		[Description("mt-xl-4")]
		MarginTopXtraLarge4,
		[Description("mt-xl-5")]
		MarginTopXtraLarge5,
		[Description("mb-0")]
		MarginBottomXtraSmall0,
		[Description("mb-1")]
		MarginBottomXtraSmall1,
		[Description("mb-2")]
		MarginBottomXtraSmall2,
		[Description("mb-3")]
		MarginBottomXtraSmall3,
		[Description("mb-4")]
		MarginBottomXtraSmall4,
		[Description("mb-5")]
		MarginBottomXtraSmall5,
		[Description("mb-sm-0")]
		MarginBottomSmall0,
		[Description("mb-sm-1")]
		MarginBottomSmall1,
		[Description("mb-sm-2")]
		MarginBottomSmall2,
		[Description("mb-sm-3")]
		MarginBottomSmall3,
		[Description("mb-sm-4")]
		MarginBottomSmall4,
		[Description("mb-sm-5")]
		MarginBottomSmall5,
		[Description("mb-md-0")]
		MarginBottomMedium0,
		[Description("mb-md-1")]
		MarginBottomMedium1,
		[Description("mb-md-2")]
		MarginBottomMedium2,
		[Description("mb-md-3")]
		MarginBottomMedium3,
		[Description("mb-md-4")]
		MarginBottomMedium4,
		[Description("mb-md-5")]
		MarginBottomMedium5,
		[Description("mb-lg-0")]
		MarginBottomLarge0,
		[Description("mb-lg-1")]
		MarginBottomLarge1,
		[Description("mb-lg-2")]
		MarginBottomLarge2,
		[Description("mb-lg-3")]
		MarginBottomLarge3,
		[Description("mb-lg-4")]
		MarginBottomLarge4,
		[Description("mb-lg-5")]
		MarginBottomLarge5,
		[Description("mb-xl-0")]
		MarginBottomXtraLarge0,
		[Description("mb-xl-1")]
		MarginBottomXtraLarge1,
		[Description("mb-xl-2")]
		MarginBottomXtraLarge2,
		[Description("mb-xl-3")]
		MarginBottomXtraLarge3,
		[Description("mb-xl-4")]
		MarginBottomXtraLarge4,
		[Description("mb-xl-5")]
		MarginBottomXtraLarge5,
		[Description("ml-0")]
		MarginLeftXtraSmall0,
		[Description("ml-1")]
		MarginLeftXtraSmall1,
		[Description("ml-2")]
		MarginLeftXtraSmall2,
		[Description("ml-3")]
		MarginLeftXtraSmall3,
		[Description("ml-4")]
		MarginLeftXtraSmall4,
		[Description("ml-5")]
		MarginLeftXtraSmall5,
		[Description("ml-sm-0")]
		MarginLeftSmall0,
		[Description("ml-sm-1")]
		MarginLeftSmall1,
		[Description("ml-sm-2")]
		MarginLeftSmall2,
		[Description("ml-sm-3")]
		MarginLeftSmall3,
		[Description("ml-sm-4")]
		MarginLeftSmall4,
		[Description("ml-sm-5")]
		MarginLeftSmall5,
		[Description("ml-md-0")]
		MarginLeftMedium0,
		[Description("ml-md-1")]
		MarginLeftMedium1,
		[Description("ml-md-2")]
		MarginLeftMedium2,
		[Description("ml-md-3")]
		MarginLeftMedium3,
		[Description("ml-md-4")]
		MarginLeftMedium4,
		[Description("ml-md-5")]
		MarginLeftMedium5,
		[Description("ml-lg-0")]
		MarginLeftLarge0,
		[Description("ml-lg-1")]
		MarginLeftLarge1,
		[Description("ml-lg-2")]
		MarginLeftLarge2,
		[Description("ml-lg-3")]
		MarginLeftLarge3,
		[Description("ml-lg-4")]
		MarginLeftLarge4,
		[Description("ml-lg-5")]
		MarginLeftLarge5,
		[Description("ml-xl-0")]
		MarginLeftXtraLarge0,
		[Description("ml-xl-1")]
		MarginLeftXtraLarge1,
		[Description("ml-xl-2")]
		MarginLeftXtraLarge2,
		[Description("ml-xl-3")]
		MarginLeftXtraLarge3,
		[Description("ml-xl-4")]
		MarginLeftXtraLarge4,
		[Description("ml-xl-5")]
		MarginLeftXtraLarge5,
		[Description("mr-0")]
		MarginRightXtraSmall0,
		[Description("mr-1")]
		MarginRightXtraSmall1,
		[Description("mr-2")]
		MarginRightXtraSmall2,
		[Description("mr-3")]
		MarginRightXtraSmall3,
		[Description("mr-4")]
		MarginRightXtraSmall4,
		[Description("mr-5")]
		MarginRightXtraSmall5,
		[Description("mr-sm-0")]
		MarginRightSmall0,
		[Description("mr-sm-1")]
		MarginRightSmall1,
		[Description("mr-sm-2")]
		MarginRightSmall2,
		[Description("mr-sm-3")]
		MarginRightSmall3,
		[Description("mr-sm-4")]
		MarginRightSmall4,
		[Description("mr-sm-5")]
		MarginRightSmall5,
		[Description("mr-md-0")]
		MarginRightMedium0,
		[Description("mr-md-1")]
		MarginRightMedium1,
		[Description("mr-md-2")]
		MarginRightMedium2,
		[Description("mr-md-3")]
		MarginRightMedium3,
		[Description("mr-md-4")]
		MarginRightMedium4,
		[Description("mr-md-5")]
		MarginRightMedium5,
		[Description("mr-lg-0")]
		MarginRightLarge0,
		[Description("mr-lg-1")]
		MarginRightLarge1,
		[Description("mr-lg-2")]
		MarginRightLarge2,
		[Description("mr-lg-3")]
		MarginRightLarge3,
		[Description("mr-lg-4")]
		MarginRightLarge4,
		[Description("mr-lg-5")]
		MarginRightLarge5,
		[Description("mr-xl-0")]
		MarginRightXtraLarge0,
		[Description("mr-xl-1")]
		MarginRightXtraLarge1,
		[Description("mr-xl-2")]
		MarginRightXtraLarge2,
		[Description("mr-xl-3")]
		MarginRightXtraLarge3,
		[Description("mr-xl-4")]
		MarginRightXtraLarge4,
		[Description("mr-xl-5")]
		MarginRightXtraLarge5,
		[Description("mx-0")]
		MarginLeftAndRightXtraSmall0,
		[Description("mx-1")]
		MarginLeftAndRightXtraSmall1,
		[Description("mx-2")]
		MarginLeftAndRightXtraSmall2,
		[Description("mx-3")]
		MarginLeftAndRightXtraSmall3,
		[Description("mx-4")]
		MarginLeftAndRightXtraSmall4,
		[Description("mx-5")]
		MarginLeftAndRightXtraSmall5,
		[Description("mx-sm-0")]
		MarginLeftAndRightSmall0,
		[Description("mx-sm-1")]
		MarginLeftAndRightSmall1,
		[Description("mx-sm-2")]
		MarginLeftAndRightSmall2,
		[Description("mx-sm-3")]
		MarginLeftAndRightSmall3,
		[Description("mx-sm-4")]
		MarginLeftAndRightSmall4,
		[Description("mx-sm-5")]
		MarginLeftAndRightSmall5,
		[Description("mx-md-0")]
		MarginLeftAndRightMedium0,
		[Description("mx-md-1")]
		MarginLeftAndRightMedium1,
		[Description("mx-md-2")]
		MarginLeftAndRightMedium2,
		[Description("mx-md-3")]
		MarginLeftAndRightMedium3,
		[Description("mx-md-4")]
		MarginLeftAndRightMedium4,
		[Description("mx-md-5")]
		MarginLeftAndRightMedium5,
		[Description("mx-lg-0")]
		MarginLeftAndRightLarge0,
		[Description("mx-lg-1")]
		MarginLeftAndRightLarge1,
		[Description("mx-lg-2")]
		MarginLeftAndRightLarge2,
		[Description("mx-lg-3")]
		MarginLeftAndRightLarge3,
		[Description("mx-lg-4")]
		MarginLeftAndRightLarge4,
		[Description("mx-lg-5")]
		MarginLeftAndRightLarge5,
		[Description("mx-xl-0")]
		MarginLeftAndRightXtraLarge0,
		[Description("mx-xl-1")]
		MarginLeftAndRightXtraLarge1,
		[Description("mx-xl-2")]
		MarginLeftAndRightXtraLarge2,
		[Description("mx-xl-3")]
		MarginLeftAndRightXtraLarge3,
		[Description("mx-xl-4")]
		MarginLeftAndRightXtraLarge4,
		[Description("mx-xl-5")]
		MarginLeftAndRightXtraLarge5,
		[Description("my-0")]
		MarginTopAndBottomXtraSmall0,
		[Description("my-1")]
		MarginTopAndBottomXtraSmall1,
		[Description("my-2")]
		MarginTopAndBottomXtraSmall2,
		[Description("my-3")]
		MarginTopAndBottomXtraSmall3,
		[Description("my-4")]
		MarginTopAndBottomXtraSmall4,
		[Description("my-5")]
		MarginTopAndBottomXtraSmall5,
		[Description("my-sm-0")]
		MarginTopAndBottomSmall0,
		[Description("my-sm-1")]
		MarginTopAndBottomSmall1,
		[Description("my-sm-2")]
		MarginTopAndBottomSmall2,
		[Description("my-sm-3")]
		MarginTopAndBottomSmall3,
		[Description("my-sm-4")]
		MarginTopAndBottomSmall4,
		[Description("my-sm-5")]
		MarginTopAndBottomSmall5,
		[Description("my-md-0")]
		MarginTopAndBottomMedium0,
		[Description("my-md-1")]
		MarginTopAndBottomMedium1,
		[Description("my-md-2")]
		MarginTopAndBottomMedium2,
		[Description("my-md-3")]
		MarginTopAndBottomMedium3,
		[Description("my-md-4")]
		MarginTopAndBottomMedium4,
		[Description("my-md-5")]
		MarginTopAndBottomMedium5,
		[Description("my-lg-0")]
		MarginTopAndBottomLarge0,
		[Description("my-lg-1")]
		MarginTopAndBottomLarge1,
		[Description("my-lg-2")]
		MarginTopAndBottomLarge2,
		[Description("my-lg-3")]
		MarginTopAndBottomLarge3,
		[Description("my-lg-4")]
		MarginTopAndBottomLarge4,
		[Description("my-lg-5")]
		MarginTopAndBottomLarge5,
		[Description("my-xl-0")]
		MarginTopAndBottomXtraLarge0,
		[Description("my-xl-1")]
		MarginTopAndBottomXtraLarge1,
		[Description("my-xl-2")]
		MarginTopAndBottomXtraLarge2,
		[Description("my-xl-3")]
		MarginTopAndBottomXtraLarge3,
		[Description("my-xl-4")]
		MarginTopAndBottomXtraLarge4,
		[Description("my-xl-5")]
		MarginTopAndBottomXtraLarge5,
		[Description("pt-0")]
		PaddingTopXtraSmall0,
		[Description("pt-1")]
		PaddingTopXtraSmall1,
		[Description("pt-2")]
		PaddingTopXtraSmall2,
		[Description("pt-3")]
		PaddingTopXtraSmall3,
		[Description("pt-4")]
		PaddingTopXtraSmall4,
		[Description("pt-5")]
		PaddingTopXtraSmall5,
		[Description("pt-sm-0")]
		PaddingTopSmall0,
		[Description("pt-sm-1")]
		PaddingTopSmall1,
		[Description("pt-sm-2")]
		PaddingTopSmall2,
		[Description("pt-sm-3")]
		PaddingTopSmall3,
		[Description("pt-sm-4")]
		PaddingTopSmall4,
		[Description("pt-sm-5")]
		PaddingTopSmall5,
		[Description("pt-md-0")]
		PaddingTopMedium0,
		[Description("pt-md-1")]
		PaddingTopMedium1,
		[Description("pt-md-2")]
		PaddingTopMedium2,
		[Description("pt-md-3")]
		PaddingTopMedium3,
		[Description("pt-md-4")]
		PaddingTopMedium4,
		[Description("pt-md-5")]
		PaddingTopMedium5,
		[Description("pt-lg-0")]
		PaddingTopLarge0,
		[Description("pt-lg-1")]
		PaddingTopLarge1,
		[Description("pt-lg-2")]
		PaddingTopLarge2,
		[Description("pt-lg-3")]
		PaddingTopLarge3,
		[Description("pt-lg-4")]
		PaddingTopLarge4,
		[Description("pt-lg-5")]
		PaddingTopLarge5,
		[Description("pt-xl-0")]
		PaddingTopXtraLarge0,
		[Description("pt-xl-1")]
		PaddingTopXtraLarge1,
		[Description("pt-xl-2")]
		PaddingTopXtraLarge2,
		[Description("pt-xl-3")]
		PaddingTopXtraLarge3,
		[Description("pt-xl-4")]
		PaddingTopXtraLarge4,
		[Description("pt-xl-5")]
		PaddingTopXtraLarge5,
		[Description("pb-0")]
		PaddingBottomXtraSmall0,
		[Description("pb-1")]
		PaddingBottomXtraSmall1,
		[Description("pb-2")]
		PaddingBottomXtraSmall2,
		[Description("pb-3")]
		PaddingBottomXtraSmall3,
		[Description("pb-4")]
		PaddingBottomXtraSmall4,
		[Description("pb-5")]
		PaddingBottomXtraSmall5,
		[Description("pb-sm-0")]
		PaddingBottomSmall0,
		[Description("pb-sm-1")]
		PaddingBottomSmall1,
		[Description("pb-sm-2")]
		PaddingBottomSmall2,
		[Description("pb-sm-3")]
		PaddingBottomSmall3,
		[Description("pb-sm-4")]
		PaddingBottomSmall4,
		[Description("pb-sm-5")]
		PaddingBottomSmall5,
		[Description("pb-md-0")]
		PaddingBottomMedium0,
		[Description("pb-md-1")]
		PaddingBottomMedium1,
		[Description("pb-md-2")]
		PaddingBottomMedium2,
		[Description("pb-md-3")]
		PaddingBottomMedium3,
		[Description("pb-md-4")]
		PaddingBottomMedium4,
		[Description("pb-md-5")]
		PaddingBottomMedium5,
		[Description("pb-lg-0")]
		PaddingBottomLarge0,
		[Description("pb-lg-1")]
		PaddingBottomLarge1,
		[Description("pb-lg-2")]
		PaddingBottomLarge2,
		[Description("pb-lg-3")]
		PaddingBottomLarge3,
		[Description("pb-lg-4")]
		PaddingBottomLarge4,
		[Description("pb-lg-5")]
		PaddingBottomLarge5,
		[Description("pb-xl-0")]
		PaddingBottomXtraLarge0,
		[Description("pb-xl-1")]
		PaddingBottomXtraLarge1,
		[Description("pb-xl-2")]
		PaddingBottomXtraLarge2,
		[Description("pb-xl-3")]
		PaddingBottomXtraLarge3,
		[Description("pb-xl-4")]
		PaddingBottomXtraLarge4,
		[Description("pb-xl-5")]
		PaddingBottomXtraLarge5,
		[Description("pl-0")]
		PaddingLeftXtraSmall0,
		[Description("pl-1")]
		PaddingLeftXtraSmall1,
		[Description("pl-2")]
		PaddingLeftXtraSmall2,
		[Description("pl-3")]
		PaddingLeftXtraSmall3,
		[Description("pl-4")]
		PaddingLeftXtraSmall4,
		[Description("pl-5")]
		PaddingLeftXtraSmall5,
		[Description("pl-sm-0")]
		PaddingLeftSmall0,
		[Description("pl-sm-1")]
		PaddingLeftSmall1,
		[Description("pl-sm-2")]
		PaddingLeftSmall2,
		[Description("pl-sm-3")]
		PaddingLeftSmall3,
		[Description("pl-sm-4")]
		PaddingLeftSmall4,
		[Description("pl-sm-5")]
		PaddingLeftSmall5,
		[Description("pl-md-0")]
		PaddingLeftMedium0,
		[Description("pl-md-1")]
		PaddingLeftMedium1,
		[Description("pl-md-2")]
		PaddingLeftMedium2,
		[Description("pl-md-3")]
		PaddingLeftMedium3,
		[Description("pl-md-4")]
		PaddingLeftMedium4,
		[Description("pl-md-5")]
		PaddingLeftMedium5,
		[Description("pl-lg-0")]
		PaddingLeftLarge0,
		[Description("pl-lg-1")]
		PaddingLeftLarge1,
		[Description("pl-lg-2")]
		PaddingLeftLarge2,
		[Description("pl-lg-3")]
		PaddingLeftLarge3,
		[Description("pl-lg-4")]
		PaddingLeftLarge4,
		[Description("pl-lg-5")]
		PaddingLeftLarge5,
		[Description("pl-xl-0")]
		PaddingLeftXtraLarge0,
		[Description("pl-xl-1")]
		PaddingLeftXtraLarge1,
		[Description("pl-xl-2")]
		PaddingLeftXtraLarge2,
		[Description("pl-xl-3")]
		PaddingLeftXtraLarge3,
		[Description("pl-xl-4")]
		PaddingLeftXtraLarge4,
		[Description("pl-xl-5")]
		PaddingLeftXtraLarge5,
		[Description("pr-0")]
		PaddingRightXtraSmall0,
		[Description("pr-1")]
		PaddingRightXtraSmall1,
		[Description("pr-2")]
		PaddingRightXtraSmall2,
		[Description("pr-3")]
		PaddingRightXtraSmall3,
		[Description("pr-4")]
		PaddingRightXtraSmall4,
		[Description("pr-5")]
		PaddingRightXtraSmall5,
		[Description("pr-sm-0")]
		PaddingRightSmall0,
		[Description("pr-sm-1")]
		PaddingRightSmall1,
		[Description("pr-sm-2")]
		PaddingRightSmall2,
		[Description("pr-sm-3")]
		PaddingRightSmall3,
		[Description("pr-sm-4")]
		PaddingRightSmall4,
		[Description("pr-sm-5")]
		PaddingRightSmall5,
		[Description("pr-md-0")]
		PaddingRightMedium0,
		[Description("pr-md-1")]
		PaddingRightMedium1,
		[Description("pr-md-2")]
		PaddingRightMedium2,
		[Description("pr-md-3")]
		PaddingRightMedium3,
		[Description("pr-md-4")]
		PaddingRightMedium4,
		[Description("pr-md-5")]
		PaddingRightMedium5,
		[Description("pr-lg-0")]
		PaddingRightLarge0,
		[Description("pr-lg-1")]
		PaddingRightLarge1,
		[Description("pr-lg-2")]
		PaddingRightLarge2,
		[Description("pr-lg-3")]
		PaddingRightLarge3,
		[Description("pr-lg-4")]
		PaddingRightLarge4,
		[Description("pr-lg-5")]
		PaddingRightLarge5,
		[Description("pr-xl-0")]
		PaddingRightXtraLarge0,
		[Description("pr-xl-1")]
		PaddingRightXtraLarge1,
		[Description("pr-xl-2")]
		PaddingRightXtraLarge2,
		[Description("pr-xl-3")]
		PaddingRightXtraLarge3,
		[Description("pr-xl-4")]
		PaddingRightXtraLarge4,
		[Description("pr-xl-5")]
		PaddingRightXtraLarge5,
		[Description("px-0")]
		PaddingLeftAndRightXtraSmall0,
		[Description("px-1")]
		PaddingLeftAndRightXtraSmall1,
		[Description("px-2")]
		PaddingLeftAndRightXtraSmall2,
		[Description("px-3")]
		PaddingLeftAndRightXtraSmall3,
		[Description("px-4")]
		PaddingLeftAndRightXtraSmall4,
		[Description("px-5")]
		PaddingLeftAndRightXtraSmall5,
		[Description("px-sm-0")]
		PaddingLeftAndRightSmall0,
		[Description("px-sm-1")]
		PaddingLeftAndRightSmall1,
		[Description("px-sm-2")]
		PaddingLeftAndRightSmall2,
		[Description("px-sm-3")]
		PaddingLeftAndRightSmall3,
		[Description("px-sm-4")]
		PaddingLeftAndRightSmall4,
		[Description("px-sm-5")]
		PaddingLeftAndRightSmall5,
		[Description("px-md-0")]
		PaddingLeftAndRightMedium0,
		[Description("px-md-1")]
		PaddingLeftAndRightMedium1,
		[Description("px-md-2")]
		PaddingLeftAndRightMedium2,
		[Description("px-md-3")]
		PaddingLeftAndRightMedium3,
		[Description("px-md-4")]
		PaddingLeftAndRightMedium4,
		[Description("px-md-5")]
		PaddingLeftAndRightMedium5,
		[Description("px-lg-0")]
		PaddingLeftAndRightLarge0,
		[Description("px-lg-1")]
		PaddingLeftAndRightLarge1,
		[Description("px-lg-2")]
		PaddingLeftAndRightLarge2,
		[Description("px-lg-3")]
		PaddingLeftAndRightLarge3,
		[Description("px-lg-4")]
		PaddingLeftAndRightLarge4,
		[Description("px-lg-5")]
		PaddingLeftAndRightLarge5,
		[Description("px-xl-0")]
		PaddingLeftAndRightXtraLarge0,
		[Description("px-xl-1")]
		PaddingLeftAndRightXtraLarge1,
		[Description("px-xl-2")]
		PaddingLeftAndRightXtraLarge2,
		[Description("px-xl-3")]
		PaddingLeftAndRightXtraLarge3,
		[Description("px-xl-4")]
		PaddingLeftAndRightXtraLarge4,
		[Description("px-xl-5")]
		PaddingLeftAndRightXtraLarge5,
		[Description("py-0")]
		PaddingTopAndBottomXtraSmall0,
		[Description("py-1")]
		PaddingTopAndBottomXtraSmall1,
		[Description("py-2")]
		PaddingTopAndBottomXtraSmall2,
		[Description("py-3")]
		PaddingTopAndBottomXtraSmall3,
		[Description("py-4")]
		PaddingTopAndBottomXtraSmall4,
		[Description("py-5")]
		PaddingTopAndBottomXtraSmall5,
		[Description("py-sm-0")]
		PaddingTopAndBottomSmall0,
		[Description("py-sm-1")]
		PaddingTopAndBottomSmall1,
		[Description("py-sm-2")]
		PaddingTopAndBottomSmall2,
		[Description("py-sm-3")]
		PaddingTopAndBottomSmall3,
		[Description("py-sm-4")]
		PaddingTopAndBottomSmall4,
		[Description("py-sm-5")]
		PaddingTopAndBottomSmall5,
		[Description("py-md-0")]
		PaddingTopAndBottomMedium0,
		[Description("py-md-1")]
		PaddingTopAndBottomMedium1,
		[Description("py-md-2")]
		PaddingTopAndBottomMedium2,
		[Description("py-md-3")]
		PaddingTopAndBottomMedium3,
		[Description("py-md-4")]
		PaddingTopAndBottomMedium4,
		[Description("py-md-5")]
		PaddingTopAndBottomMedium5,
		[Description("py-lg-0")]
		PaddingTopAndBottomLarge0,
		[Description("py-lg-1")]
		PaddingTopAndBottomLarge1,
		[Description("py-lg-2")]
		PaddingTopAndBottomLarge2,
		[Description("py-lg-3")]
		PaddingTopAndBottomLarge3,
		[Description("py-lg-4")]
		PaddingTopAndBottomLarge4,
		[Description("py-lg-5")]
		PaddingTopAndBottomLarge5,
		[Description("py-xl-0")]
		PaddingTopAndBottomXtraLarge0,
		[Description("py-xl-1")]
		PaddingTopAndBottomXtraLarge1,
		[Description("py-xl-2")]
		PaddingTopAndBottomXtraLarge2,
		[Description("py-xl-3")]
		PaddingTopAndBottomXtraLarge3,
		[Description("py-xl-4")]
		PaddingTopAndBottomXtraLarge4,
		[Description("py-xl-5")]
		PaddingTopAndBottomXtraLarge5,
		}

	public enum NavBarExpand{
		None,
		[Description("navbar-expand")]
		ExpandXtraSmall,
		[Description("navbar-expand-sm")]
		ExpandSmall,
		[Description("navbar-expand-md")]
		ExpandMedium,
		[Description("navbar-expand-lg")]
		ExpandLarge,
		[Description("navbar-expand-xl")]
		ExpandXtraLarge,
	}
	
	public enum Display{
		None,
		[Description("d-none")]
		XtraSmallNone,
		[Description("d-inline")]
		XtraSmallInline,
		[Description("d-inline-block")]
		XtraSmallInlineBlock,
		[Description("d-block")]
		XtraSmallBlock,
		[Description("d-table")]
		XtraSmallTable,
		[Description("d-table-cell")]
		XtraSmallTableCell,
		[Description("d-table-row")]
		XtraSmallTableRow,
		[Description("d-flex")]
		XtraSmallFlex,
		[Description("d-inline-flex")]
		XtraSmallInlineFlex,
		[Description("d-sm-none")]
		SmallNone,
		[Description("d-sm-inline")]
		SmallInline,
		[Description("d-sm-inline-block")]
		SmallInlineBlock,
		[Description("d-sm-block")]
		SmallBlock,
		[Description("d-sm-table")]
		SmallTable,
		[Description("d-sm-table-cell")]
		SmallTableCell,
		[Description("d-sm-table-row")]
		SmallTableRow,
		[Description("d-sm-flex")]
		SmallFlex,
		[Description("d-sm-inline-flex")]
		SmallInlineFlex,
		[Description("d-md-none")]
		MediumNone,
		[Description("d-md-inline")]
		MediumInline,
		[Description("d-md-inline-block")]
		MediumInlineBlock,
		[Description("d-md-block")]
		MediumBlock,
		[Description("d-md-table")]
		MediumTable,
		[Description("d-md-table-cell")]
		MediumTableCell,
		[Description("d-md-table-row")]
		MediumTableRow,
		[Description("d-md-flex")]
		MediumFlex,
		[Description("d-md-inline-flex")]
		MediumInlineFlex,
		[Description("d-lg-none")]
		LargeNone,
		[Description("d-lg-inline")]
		LargeInline,
		[Description("d-lg-inline-block")]
		LargeInlineBlock,
		[Description("d-lg-block")]
		LargeBlock,
		[Description("d-lg-table")]
		LargeTable,
		[Description("d-lg-table-cell")]
		LargeTableCell,
		[Description("d-lg-table-row")]
		LargeTableRow,
		[Description("d-lg-flex")]
		LargeFlex,
		[Description("d-lg-inline-flex")]
		LargeInlineFlex,
		[Description("d-xl-none")]
		XtraLargeNone,
		[Description("d-xl-inline")]
		XtraLargeInline,
		[Description("d-xl-inline-block")]
		XtraLargeInlineBlock,
		[Description("d-xl-block")]
		XtraLargeBlock,
		[Description("d-xl-table")]
		XtraLargeTable,
		[Description("d-xl-table-cell")]
		XtraLargeTableCell,
		[Description("d-xl-table-row")]
		XtraLargeTableRow,
		[Description("d-xl-flex")]
		XtraLargeFlex,
		[Description("d-xl-inline-flex")]
		XtraLargeInlineFlex,
	}
}