using System.ComponentModel;

namespace WeStrap
{
    public enum Color
    {
        None,
        [Description("active")]
        Active,
        [Description("blue")]
        Blue,
        [Description("indigo")]
        Indigo,
        [Description("pink")]
        Pink,
        [Description("red")]
        Red,
        [Description("orange")]
        Orange,
        [Description("yellow")]
        Yellow,
        [Description("green")]
        Green,
        [Description("teal")]
        Teal,
        [Description("cyan")]
        Cyan,
        [Description("white")]
        White,
        [Description("gray")]
        Gray,
        [Description("gray-dark")]
        GrayDark,
        [Description("primary")]
        Primary,
        [Description("secondary")]
        Secondary,
        [Description("success")]
        Success,
        [Description("info")]
        Info,
        [Description("warning")]
        Warning,
        [Description("danger")]
        Danger,
        [Description("light")]
        Light,
        [Description("dark")]
        Dark,
        [Description("link")]
        Link,
        [Description("aliceblue")]
        aliceblue,
        [Description("antiquewhite")]
        antiquewhite,
        [Description("aqua")]
        aqua,
        [Description("aquamarine")]
        aquamarine,
        [Description("azure")]
        azure,
        [Description("beige")]
        beige,
        [Description("bisque")]
        bisque,
        [Description("black")]
        black,
        [Description("blanchedalmond")]
        blanchedalmond,
        [Description("blue")]
        blue,
        [Description("blueviolet")]
        blueviolet,
        [Description("brown")]
        brown,
        [Description("burlywood")]
        burlywood,
        [Description("cadetblue")]
        cadetblue,
        [Description("chartreuse")]
        chartreuse,
        [Description("chocolate")]
        chocolate,
        [Description("coral")]
        coral,
        [Description("cornflowerblue")]
        cornflowerblue,
        [Description("cornsilk")]
        cornsilk,
        [Description("crimson")]
        crimson,
        [Description("cyan")]
        cyan,
        [Description("darkblue")]
        darkblue,
        [Description("darkcyan")]
        darkcyan,
        [Description("darkgoldenrod")]
        darkgoldenrod,
        [Description("darkgray")]
        darkgray,
        [Description("darkgreen")]
        darkgreen,
        [Description("darkkhaki")]
        darkkhaki,
        [Description("darkmagenta")]
        darkmagenta,
        [Description("darkolivegreen")]
        darkolivegreen,
        [Description("darkorange")]
        darkorange,
        [Description("darkorchid")]
        darkorchid,
        [Description("darkred")]
        darkred,
        [Description("darksalmon")]
        darksalmon,
        [Description("darkseagreen")]
        darkseagreen,
        [Description("darkslateblue")]
        darkslateblue,
        [Description("darkslategray")]
        darkslategray,
        [Description("darkturquoise")]
        darkturquoise,
        [Description("darkviolet")]
        darkviolet,
        [Description("deeppink")]
        deeppink,
        [Description("deepskyblue")]
        deepskyblue,
        [Description("dimgray")]
        dimgray,
        [Description("dodgerblue")]
        dodgerblue,
        [Description("firebrick")]
        firebrick,
        [Description("floralwhite")]
        floralwhite,
        [Description("forestgreen")]
        forestgreen,
        [Description("fuchsia")]
        fuchsia,
        [Description("gainsboro")]
        gainsboro,
        [Description("ghostwhite")]
        ghostwhite,
        [Description("gold")]
        gold,
        [Description("goldenrod")]
        goldenrod,
        [Description("gray")]
        gray,
        [Description("green")]
        green,
        [Description("greenyellow")]
        greenyellow,
        [Description("honeydew")]
        honeydew,
        [Description("hotpink")]
        hotpink,
        [Description("indianred")]
        indianred,
        [Description("indigo")]
        indigo,
        [Description("ivory")]
        ivory,
        [Description("khaki")]
        khaki,
        [Description("lavender")]
        lavender,
        [Description("lavenderblush")]
        lavenderblush,
        [Description("lawngreen")]
        lawngreen,
        [Description("lemonchiffon")]
        lemonchiffon,
        [Description("lightblue")]
        lightblue,
        [Description("lightcoral")]
        lightcoral,
        [Description("lightcyan")]
        lightcyan,
        [Description("lightgoldenrodyellow")]
        lightgoldenrodyellow,
        [Description("lightgray")]
        lightgray,
        [Description("lightgreen")]
        lightgreen,
        [Description("lightpink")]
        lightpink,
        [Description("lightsalmon")]
        lightsalmon,
        [Description("lightseagreen")]
        lightseagreen,
        [Description("lightskyblue")]
        lightskyblue,
        [Description("lightslategray")]
        lightslategray,
        [Description("lightsteelblue")]
        lightsteelblue,
        [Description("lightyellow")]
        lightyellow,
        [Description("lime")]
        lime,
        [Description("limegreen")]
        limegreen,
        [Description("linen")]
        linen,
        [Description("magenta")]
        magenta,
        [Description("maroon")]
        maroon,
        [Description("mediumaquamarine")]
        mediumaquamarine,
        [Description("mediumblue")]
        mediumblue,
        [Description("mediumorchid")]
        mediumorchid,
        [Description("mediumpurple")]
        mediumpurple,
        [Description("mediumseagreen")]
        mediumseagreen,
        [Description("mediumslateblue")]
        mediumslateblue,
        [Description("mediumspringgreen")]
        mediumspringgreen,
        [Description("mediumturquoise")]
        mediumturquoise,
        [Description("mediumvioletred")]
        mediumvioletred,
        [Description("midnightblue")]
        midnightblue,
        [Description("mintcream")]
        mintcream,
        [Description("mistyrose")]
        mistyrose,
        [Description("moccasin")]
        moccasin,
        [Description("navajowhite")]
        navajowhite,
        [Description("navy")]
        navy,
        [Description("oldlace")]
        oldlace,
        [Description("olive")]
        olive,
        [Description("olivedrab")]
        olivedrab,
        [Description("orange")]
        orange,
        [Description("orangered")]
        orangered,
        [Description("orchid")]
        orchid,
        [Description("palegoldenrod")]
        palegoldenrod,
        [Description("palegreen")]
        palegreen,
        [Description("paleturquoise")]
        paleturquoise,
        [Description("palevioletred")]
        palevioletred,
        [Description("papayawhip")]
        papayawhip,
        [Description("peachpuff")]
        peachpuff,
        [Description("peru")]
        peru,
        [Description("pink")]
        pink,
        [Description("plum")]
        plum,
        [Description("powderblue")]
        powderblue,
        [Description("purple")]
        purple,
        [Description("rebeccapurple")]
        rebeccapurple,
        [Description("red")]
        red,
        [Description("rosybrown")]
        rosybrown,
        [Description("royalblue")]
        royalblue,
        [Description("saddlebrown")]
        saddlebrown,
        [Description("salmon")]
        salmon,
        [Description("sandybrown")]
        sandybrown,
        [Description("seagreen")]
        seagreen,
        [Description("seashell")]
        seashell,
        [Description("sienna")]
        sienna,
        [Description("silver")]
        silver,
        [Description("skyblue")]
        skyblue,
        [Description("slateblue")]
        slateblue,
        [Description("slategray")]
        slategray,
        [Description("snow")]
        snow,
        [Description("springgreen")]
        springgreen,
        [Description("steelblue")]
        steelblue,
        [Description("tan")]
        tan,
        [Description("teal")]
        teal,
        [Description("thistle")]
        thistle,
        [Description("tomato")]
        tomato,
        [Description("turquoise")]
        turquoise,
        [Description("violet")]
        violet,
        [Description("wheat")]
        wheat,
        [Description("white")]
        white,
        [Description("whitesmoke")]
        whitesmoke,
        [Description("yellow")]
        yellow,
        [Description("yellowgreen")]
        yellowgreen,
            }
}

