using System.ComponentModel;
namespace WeStrap
{
    public enum WeColumn
    {
        None,
        [Description("col-1")]
        xs1,
        [Description("col-2")]
        xs2,
        [Description("col-3")]
        xs3,
        [Description("col-4")]
        xs4,
        [Description("col-5")]
        xs5,
        [Description("col-6")]
        xs6,
        [Description("col-7")]
        xs7,
        [Description("col-8")]
        xs8,
        [Description("col-9")]
        xs9,
        [Description("col-10")]
        xs10,
        [Description("col-11")]
        xs11,
        [Description("col-12")]
        xs12,
        [Description("col-sm-1")]
        sm1,
        [Description("col-sm-2")]
        sm2,
        [Description("col-sm-3")]
        sm3,
        [Description("col-sm-4")]
        sm4,
        [Description("col-sm-5")]
        sm5,
        [Description("col-sm-6")]
        sm6,
        [Description("col-sm-7")]
        sm7,
        [Description("col-sm-8")]
        sm8,
        [Description("col-sm-9")]
        sm9,
        [Description("col-sm-10")]
        sm10,
        [Description("col-sm-11")]
        sm11,
        [Description("col-sm-12")]
        sm12,
        [Description("col-md-1")]
        md1,
        [Description("col-md-2")]
        md2,
        [Description("col-md-3")]
        md3,
        [Description("col-md-4")]
        md4,
        [Description("col-md-5")]
        md5,
        [Description("col-md-6")]
        md6,
        [Description("col-md-7")]
        md7,
        [Description("col-md-8")]
        md8,
        [Description("col-md-9")]
        md9,
        [Description("col-md-10")]
        md10,
        [Description("col-md-11")]
        md11,
        [Description("col-md-12")]
        md12,
        [Description("col-lg-1")]
        lg1,
        [Description("col-lg-2")]
        lg2,
        [Description("col-lg-3")]
        lg3,
        [Description("col-lg-4")]
        lg4,
        [Description("col-lg-5")]
        lg5,
        [Description("col-lg-6")]
        lg6,
        [Description("col-lg-7")]
        lg7,
        [Description("col-lg-8")]
        lg8,
        [Description("col-lg-9")]
        lg9,
        [Description("col-lg-10")]
        lg10,
        [Description("col-lg-11")]
        lg11,
        [Description("col-lg-12")]
        lg12,
        [Description("col-xl-1")]
        xl1,
        [Description("col-xl-2")]
        xl2,
        [Description("col-xl-3")]
        xl3,
        [Description("col-xl-4")]
        xl4,
        [Description("col-xl-5")]
        xl5,
        [Description("col-xl-6")]
        xl6,
        [Description("col-xl-7")]
        xl7,
        [Description("col-xl-8")]
        xl8,
        [Description("col-xl-9")]
        xl9,
        [Description("col-xl-10")]
        xl10,
        [Description("col-xl-11")]
        xl11,
        [Description("col-xl-12")]
        xl12,
    }
}