using System.ComponentModel;
namespace WeStrap
{
    public enum FixedHeight
    {
        None,
        [Description("fixed_height_200")]
        Height200,
        [Description("fixed_height_210")]
        Height210,
        [Description("fixed_height_220")]
        Height220,
        [Description("fixed_height_230")]
        Height230,
        [Description("fixed_height_240")]
        Height240,
        [Description("fixed_height_250")]
        Height250,
        [Description("fixed_height_260")]
        Height260,
        [Description("fixed_height_270")]
        Height270,
        [Description("fixed_height_280")]
        Height280,
        [Description("fixed_height_290")]
        Height290,
        [Description("fixed_height_300")]
        Height300,
        [Description("fixed_height_310")]
        Height310,
        [Description("fixed_height_320")]
        Height320,
        [Description("fixed_height_330")]
        Height330,
        [Description("fixed_height_340")]
        Height340,
        [Description("fixed_height_350")]
        Height350,
        [Description("fixed_height_360")]
        Height360,
        [Description("fixed_height_370")]
        Height370,
        [Description("fixed_height_380")]
        Height380,
        [Description("fixed_height_390")]
        Height390,
        [Description("fixed_height_400")]
        Height400,
        [Description("fixed_height_410")]
        Height410,
        [Description("fixed_height_420")]
        Height420,
        [Description("fixed_height_430")]
        Height430,
        [Description("fixed_height_440")]
        Height440,
        [Description("fixed_height_450")]
        Height450,
        [Description("fixed_height_460")]
        Height460,
        [Description("fixed_height_470")]
        Height470,
        [Description("fixed_height_480")]
        Height480,
        [Description("fixed_height_490")]
        Height490,
        [Description("fixed_height_500")]
        Height500,

    }
}