
namespace WeStrap{
using System.ComponentModel;
	public enum Tag{
		[Description("a")]
		A,
		[Description("abbr")]
		Abbr,
		[Description("acronym")]
		Acronym,
		[Description("address")]
		Address,
		[Description("applet")]
		Applet,
		[Description("area")]
		Area,
		[Description("article")]
		Article,
		[Description("aside")]
		Aside,
		[Description("audio")]
		Audio,
		[Description("b")]
		B,
		[Description("base")]
		Base,
		[Description("basefont")]
		Basefont,
		[Description("bdi")]
		Bdi,
		[Description("bdo")]
		Bdo,
		[Description("big")]
		Big,
		[Description("blockquote")]
		Blockquote,
		[Description("body")]
		Body,
		[Description("br")]
		Br,
		[Description("button")]
		Button,
		[Description("canvas")]
		Canvas,
		[Description("caption")]
		Caption,
		[Description("center")]
		Center,
		[Description("cite")]
		Cite,
		[Description("code")]
		Code,
		[Description("col")]
		Col,
		[Description("colgroup")]
		Colgroup,
		[Description("data")]
		Data,
		[Description("datalist")]
		Datalist,
		[Description("dd")]
		Dd,
		[Description("del")]
		Del,
		[Description("details")]
		Details,
		[Description("dfn")]
		Dfn,
		[Description("dialog")]
		Dialog,
		[Description("dir")]
		Dir,
		[Description("div")]
		Div,
		[Description("dl")]
		Dl,
		[Description("dt")]
		Dt,
		[Description("em")]
		Em,
		[Description("embed")]
		Embed,
		[Description("fieldset")]
		Fieldset,
		[Description("figcaption")]
		Figcaption,
		[Description("figure")]
		Figure,
		[Description("font")]
		Font,
		[Description("footer")]
		Footer,
		[Description("form")]
		Form,
		[Description("frame")]
		Frame,
		[Description("frameset")]
		Frameset,
		[Description("h1")]
		H1,
		[Description("h2")]
		H2,
		[Description("h3")]
		H3,
		[Description("h4")]
		H4,
		[Description("h5")]
		H5,
		[Description("h6")]
		H6,
		[Description("head")]
		Head,
		[Description("header")]
		Header,
		[Description("hr")]
		Hr,
		[Description("html")]
		Html,
		[Description("i")]
		I,
		[Description("iframe")]
		Iframe,
		[Description("img")]
		Img,
		[Description("input")]
		Input,
		[Description("ins")]
		Ins,
		[Description("kbd")]
		Kbd,
		[Description("label")]
		Label,
		[Description("legend")]
		Legend,
		[Description("li")]
		Li,
		[Description("link")]
		Link,
		[Description("main")]
		Main,
		[Description("map")]
		Map,
		[Description("mark")]
		Mark,
		[Description("meta")]
		Meta,
		[Description("meter")]
		Meter,
		[Description("nav")]
		Nav,
		[Description("noframes")]
		Noframes,
		[Description("noscript")]
		Noscript,
		[Description("object")]
		Object,
		[Description("ol")]
		Ol,
		[Description("optgroup")]
		Optgroup,
		[Description("option")]
		Option,
		[Description("output")]
		Output,
		[Description("p")]
		P,
		[Description("param")]
		Param,
		[Description("picture")]
		Picture,
		[Description("pre")]
		Pre,
		[Description("progress")]
		Progress,
		[Description("q")]
		Q,
		[Description("rp")]
		Rp,
		[Description("rt")]
		Rt,
		[Description("ruby")]
		Ruby,
		[Description("s")]
		S,
		[Description("samp")]
		Samp,
		[Description("script")]
		Script,
		[Description("section")]
		Section,
		[Description("select")]
		Select,
		[Description("small")]
		Small,
		[Description("source")]
		Source,
		[Description("span")]
		Span,
		[Description("strike")]
		Strike,
		[Description("strong")]
		Strong,
		[Description("style")]
		Style,
		[Description("sub")]
		Sub,
		[Description("summary")]
		Summary,
		[Description("sup")]
		Sup,
		[Description("svg")]
		Svg,
		[Description("table")]
		Table,
		[Description("tbody")]
		Tbody,
		[Description("td")]
		Td,
		[Description("template")]
		Template,
		[Description("textarea")]
		Textarea,
		[Description("tfoot")]
		Tfoot,
		[Description("th")]
		Th,
		[Description("thead")]
		Thead,
		[Description("time")]
		Time,
		[Description("title")]
		Title,
		[Description("tr")]
		Tr,
		[Description("track")]
		Track,
		[Description("tt")]
		Tt,
		[Description("u")]
		U,
		[Description("ul")]
		Ul,
		[Description("var")]
		Var,
		[Description("video")]
		Video,
		[Description("wbr")]
		Wbr,
		}

}